all_gather_list_size: 16384
amp: false
amp_batch_retries: 2
amp_init_scale: 128
amp_scale_window: null
azureml_logging: false
batch_size: null
batch_size_valid: null
beam: 20
beam_size_token: 100
beam_threshold: 25.0
best_checkpoint_metric: loss
bf16: false
bpe: null
broadcast_buffers: false
bucket_cap_mb: 25
checkpoint_shard_count: 1
checkpoint_suffix: ''
combine_valid_subsets: null
constraints: null
cpu: false
cpu_offload: false
criterion: ctc
curriculum: 0
data: ''
data_buffer_size: 10
dataset_impl: null
ddp_backend: pytorch_ddp
ddp_comm_hook: none
decoding_format: null
device_id: 0
disable_validation: false
distributed_backend: nccl
distributed_init_method: null
distributed_no_spawn: false
distributed_num_procs: 1
distributed_port: -1
distributed_rank: 0
distributed_world_size: 1
diverse_beam_groups: -1
diverse_beam_strength: 0.5
diversity_rate: -1.0
dump_emissions: null
dump_features: null
empty_cache_freq: 0
eos: 2
eval_bleu: false
eval_bleu_args: '{}'
eval_bleu_detok: space
eval_bleu_detok_args: '{}'
eval_bleu_print_samples: false
eval_bleu_remove_bpe: null
eval_tokenized_bleu: false
fast_stat_sync: false
find_unused_parameters: false
finetune_from_model: null
fix_batches_to_gpus: false
fixed_validation_seed: null
force_anneal: null
fp16: false
fp16_init_scale: 128
fp16_no_flatten_grads: false
fp16_scale_tolerance: 0.0
fp16_scale_window: null
fp32_reduce_scatter: false
gen_subset: deploy
heartbeat_timeout: -1
ignore_unused_valid_subsets: false
iter_decode_eos_penalty: 0.0
iter_decode_force_max_iter: false
iter_decode_max_iter: 10
iter_decode_with_beam: 1
iter_decode_with_external_reranker: false
keep_best_checkpoints: -1
keep_interval_updates: -1
keep_interval_updates_pattern: -1
keep_last_epochs: -1
kenlm_model: ../kenlm/lm_southtelecom_vnpt2.bin
kspmodel: null
labels: ltr
left_pad_source: true
left_pad_target: false
lenpen: 1
lexicon: lexicon.txt
lm_path: null
lm_weight: 0.5
load_alignments: false
load_checkpoint_on_all_dp_ranks: false
load_emissions: null
localsgd_frequency: 3
log_file: null
log_format: null
log_interval: 100
lr_scheduler: fixed
lr_shrink: 0.1
match_source_len: false
max_len_a: 0
max_len_b: 200
max_source_positions: 1024
max_target_positions: 1024
max_tokens: 4000000
max_tokens_valid: null
max_valid_steps: null
maximize_best_checkpoint_metric: false
memory_efficient_bf16: false
memory_efficient_fp16: false
min_len: 1
min_loss_scale: 0.0001
model_overrides: '{}'
model_parallel_size: 1
nbest: 1
no_beamable_mm: false
no_early_stop: false
no_epoch_checkpoints: false
no_last_checkpoints: false
no_progress_bar: false
no_repeat_ngram_size: 0
no_reshard_after_forward: false
no_save: false
no_save_optimizer_state: false
no_seed_provided: false
nprocs_per_node: 1
num_batch_buckets: 0
num_shards: 1
num_workers: 1
on_cpu_convert_precision: false
optimizer: null
optimizer_overrides: '{}'
pad: 1
path: /home/damnguyen/Speech/fairseq/outputs/2021-11-15/20-50-52/checkpoints/checkpoint_best.pt
patience: -1
pipeline_balance: null
pipeline_checkpoint: never
pipeline_chunks: 0
pipeline_decoder_balance: null
pipeline_decoder_devices: null
pipeline_devices: null
pipeline_encoder_balance: null
pipeline_encoder_devices: null
pipeline_model_parallel: false
plasma_path: /tmp/plasma
post_process: letter
prefix_size: 0
print_alignment: null
print_step: false
profile: false
quantization_config_path: null
quiet: false
replace_unk: null
required_batch_size_multiple: 8
required_seq_len_multiple: 1
reset_dataloader: false
reset_logging: false
reset_lr_scheduler: false
reset_meters: false
reset_optimizer: false
restore_file: checkpoint_last.pt
results_path: null
retain_dropout: false
retain_dropout_modules: null
retain_iter_history: false
rnnt_decoding_type: greedy
rnnt_len_penalty: -0.5
sacrebleu: false
sampling: false
sampling_topk: -1
sampling_topp: -1.0
save_dir: checkpoints
save_interval: 1
save_interval_updates: 0
score_reference: false
scoring: bleu
seed: 1
shard_id: 0
sil_weight: 0.0
simul_type: null
skip_invalid_size_inputs_valid_test: false
slowmo_algorithm: LocalSGD
slowmo_momentum: null
source_lang: null
suppress_crashes: false
target_lang: null
task: audio_finetuning
temperature: 1.0
tensorboard_logdir: null
threshold_loss_scale: null
tokenizer: null
tpu: false
train_subset: train
truncate_source: false
unit_lm: true
unk: 3
unk_weight: -.inf
unkpen: 0
unnormalized: false
upsample_primary: -1
use_plasma_view: false
use_sharded_state: false
user_dir: null
valid_subset: valid
validate_after_updates: 0
validate_interval: 1
validate_interval_updates: 0
w2l_decoder: kenlm
wandb_project: null
warmup_updates: 0
wfstlm: null
word_score: -1.0
write_checkpoints_asynchronously: false
zero_sharding: none
